#!/usr/bin/env bash
# Provision a FRESH Debian/Ubuntu VM (e.g. GCP) for AppSecWatch:
#   system packages + Docker Engine → source at /opt/appsecwatch → .env with a
#   generated API key → mmdb dir. It does NOT build or start anything; that is
#   scripts/deploy.sh, the layer above this one.
#
# Run as root, either from a checkout:
#     sudo bash scripts/provision.sh
# or standalone on a bare box (it clones the repo itself):
#     curl -fsSL https://raw.githubusercontent.com/ktappsec/AppSecWatch/main/scripts/provision.sh | sudo bash
#
# Idempotent: safe to re-run. It NEVER overwrites an existing .env (that is where
# the API key lives) and never touches the `appsecwatch-data` volume.
set -euo pipefail

# --- tunables (override via env) ---
INSTALL_DIR="${INSTALL_DIR:-/opt/appsecwatch}"
REPO_URL="${REPO_URL:-https://github.com/ktappsec/AppSecWatch.git}"
REPO_REF="${REPO_REF:-main}"
# The image build needs room for Chromium + nuclei templates + the Go toolchain +
# the Node build stage. Measured cold build peaks around 8 GB including cache.
MIN_FREE_GB="${MIN_FREE_GB:-12}"

say()  { printf '\n\033[1;36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$1" >&2; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root:  sudo bash scripts/provision.sh" >&2
  exit 1
fi
export DEBIAN_FRONTEND=noninteractive

# --- 1. base packages ---
say "Installing base packages…"
apt-get update -y
apt-get install -y ca-certificates curl gnupg git rsync openssl

# --- 2. Docker Engine (official repo) ---
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker Engine…"
  . /etc/os-release   # provides $ID (debian|ubuntu) and $VERSION_CODENAME
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  say "Docker $(docker --version) already present — skipping."
fi
systemctl enable --now docker
# `restart: unless-stopped` in docker-compose.yml + an enabled docker.service is
# what brings the stack back after a reboot — there is no systemd unit of our own.

# --- 3. place the source at the canonical location ---
SRC_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]:-}" ]; then
  SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

if [ -d "$INSTALL_DIR/.git" ]; then
  say "Source already at ${INSTALL_DIR} — fetching ${REPO_REF}…"
  git -C "$INSTALL_DIR" fetch --prune origin
  git -C "$INSTALL_DIR" checkout "$REPO_REF"
  git -C "$INSTALL_DIR" pull --ff-only origin "$REPO_REF"
elif [ -n "$SRC_DIR" ] && [ -f "$SRC_DIR/docker-compose.yml" ] && [ "$SRC_DIR" != "$INSTALL_DIR" ]; then
  # Run from a checkout that was copied onto the box (scp/rsync) — mirror it.
  say "Installing source to ${INSTALL_DIR} (from ${SRC_DIR})…"
  mkdir -p "$INSTALL_DIR"
  rsync -a --exclude .git --exclude .env --exclude .venv --exclude node_modules \
        --exclude web/.next --exclude web/out --exclude runs \
        "$SRC_DIR/" "$INSTALL_DIR/"
elif [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
  # Standalone bootstrap (curl | bash) — clone it.
  say "Cloning ${REPO_URL} (${REPO_REF}) → ${INSTALL_DIR}…"
  git clone --branch "$REPO_REF" "$REPO_URL" "$INSTALL_DIR"
fi

# --- 4. .env — generated once, NEVER clobbered (it holds the API key) ---
# APPSECWATCH_API_KEYS is required by docker-compose.yml (`:?`). Without it auth is
# OPEN, and an open server has no scope ceiling at all — it will scan any root a
# caller names. That matters the moment a Cloudflare Tunnel is put in front of it.
if [ ! -f "$INSTALL_DIR/.env" ]; then
  say "Generating ${INSTALL_DIR}/.env with a fresh API key + Basic-auth password…"
  API_KEY="$(openssl rand -hex 32)"
  # Base64 of 18 random bytes, minus the URL-hostile characters. Long enough to
  # resist online guessing, short enough to type into a browser prompt.
  BASIC_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
  BASIC_USER="${BASIC_USER:-appsec}"
  cat > "$INSTALL_DIR/.env" <<EOF
# AppSecWatch deployment secrets. Generated by scripts/provision.sh — keep private.
#
# API auth. Comma-separate for multiple keys. NEVER leave this blank: an unset
# value means auth is OPEN and there is no server-side scan-scope ceiling.
APPSECWATCH_API_KEYS=${API_KEY}

# HTTP Basic front door (\`user:password\`; only the FIRST colon separates, so the
# password may contain more). This is the gate that covers the STATIC UI — the
# API key is a per-route dependency and does NOT protect it — so without this the
# SPA shell is readable by anyone who can reach the port. Clearing this prompt
# also satisfies the API, so a browser user needs no second credential.
APPSECWATCH_BASIC_AUTH=${BASIC_USER}:${BASIC_PASSWORD}

# Host interface the UI/API is published on. Default 127.0.0.1 = reachable only
# from the box itself, which is what you want behind a Cloudflare Tunnel.
# Set to 0.0.0.0 only if you intend to expose the port directly.
APPSECWATCH_BIND=127.0.0.1

# Optional: HMAC secret for outbound webhook signatures.
#APPSECWATCH_WEBHOOK_SECRET=

# Optional: only used by the opt-in ZAP sidecar (docker compose --profile zap).
#ZAP_API_KEY=
EOF
  chmod 600 "$INSTALL_DIR/.env"
else
  say "Keeping existing ${INSTALL_DIR}/.env (not overwritten)."
fi

# --- 5. MMDB bind-mount dir (optional feature; the mount must exist regardless) ---
# ASN/org enrichment is display-only and degrades cleanly when the file is absent,
# but docker-compose bind-mounts ./mmdb, so the directory has to be there.
install -d -m 755 "$INSTALL_DIR/mmdb"
if [ ! -f "$INSTALL_DIR/mmdb/GeoLite2-ASN.mmdb" ]; then
  warn "No mmdb/GeoLite2-ASN.mmdb — ASN/org enrichment will be disabled (optional, not a gate)."
fi

# --- 6. disk preflight (advisory: the build is large, the failure mode is ugly) ---
FREE_GB="$(df -BG --output=avail "$INSTALL_DIR" | tail -1 | tr -dc '0-9')"
if [ "${FREE_GB:-0}" -lt "$MIN_FREE_GB" ]; then
  warn "Only ${FREE_GB}G free at ${INSTALL_DIR}; the image build wants ~${MIN_FREE_GB}G."
  warn "Grow the disk, or free space, before scripts/deploy.sh (a build that fills the"
  warn "disk leaves a half-written layer that must be cleared with 'docker system prune -af')."
fi

say "Provisioning complete."
echo "  $(docker --version) · $(docker compose version)"
cat <<EOF

Source:  ${INSTALL_DIR}
Secrets: ${INSTALL_DIR}/.env   (mode 600)

Browser login (HTTP Basic prompt on first visit):
  $(grep -E '^APPSECWATCH_BASIC_AUTH=' "$INSTALL_DIR/.env" | cut -d= -f2- | sed 's/:/  \/  password: /')

API key (for scripts; also usable in the UI Settings field):
  $(grep -E '^APPSECWATCH_API_KEYS=' "$INSTALL_DIR/.env" | cut -d= -f2-)

Next:
  1) sudo bash ${INSTALL_DIR}/scripts/deploy.sh    # build + start + health check
  2) point a Cloudflare Tunnel at http://localhost:8080
  3) open the UI, then Settings → set the LLM endpoint/key (a scan is gated on it)

Updates later:  sudo bash ${INSTALL_DIR}/scripts/deploy.sh   (it pulls, rebuilds, restarts)
EOF
